# Generated by Django 3.2.6 on 2021-08-15 00:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('default', models.BooleanField(default=False, verbose_name='main')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_payment_gateway.paymentgateway_set+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'payment gateway',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('CREDIT_CARD', 'Credit Card'), ('BANK_SLIP', 'Bank Slip')], max_length=255, verbose_name='name')),
                ('allow_installments', models.BooleanField(default=True, verbose_name='with installments')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'payment method',
            },
        ),
        migrations.CreateModel(
            name='PagarmeGateway',
            fields=[
                ('paymentgateway_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payment_gateway.paymentgateway')),
                ('api_key', models.CharField(max_length=255)),
                ('encryption_key', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Pagar.me',
            },
            bases=('payment_gateway.paymentgateway',),
        ),
        migrations.CreateModel(
            name='PaymentMethodConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('max_installments', models.SmallIntegerField(blank=True, help_text='If you do not allow installments, leave as 0', null=True, verbose_name='installment')),
                ('discount_percentage', models.PositiveSmallIntegerField(blank=True, help_text='Discount in % (if not, leave it at 0)', null=True, verbose_name='installment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment_gateway.paymentmethod', verbose_name='payment method')),
            ],
            options={
                'verbose_name': 'configuration of payment methods',
            },
        ),
    ]
