# Generated by Django 3.2.6 on 2021-08-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateway', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(choices=[('CREDIT CARD', 'Credit Card'), ('BANK SLIP', 'Bank Slip')], max_length=255, verbose_name='name'),
        ),
    ]
