#!/bin/bash

set +e

echo '########################'
echo 'BEGIN: docker-compose up'
echo '########################'
echo 'View this app in your web browser at'
echo 'http://localhost:8000/'
docker-compose up
